### ISSUE TITLE
Add option to display node types (like class names)

### ISSUE THREAD

**Issue by skjardenCode** [blackflux/object-treeify#1063]
Hey there,

I'm using `object-treeify` to display various data in my projects and it is of great help. Now I wanted to debug a class hierarchy while working on a small parser.

When I `console.log` my parsed expression tree/object (without `object-treeify`), I get:

```
> console.log( expression );

 AndOperator {
  leftOperand: EqualsOperator {
    leftOperand: DotOperator {
      leftOperand: [RefLiteral],
      rightOperand: [RefLiteral]
    },
    rightOperand: NumberLiteral { value: 1000 }
  },
  rightOperand: BooleanLiteral { value: true }
}
```

When I output that expression with `object-treeify`, I get:

```
> console.log( treeify( expression ) );

├─ leftOperand
│  ├─ leftOperand
│  │  ├─ leftOperand
│  │  │  └─ value: message
│  │  └─ rightOperand
│  │     └─ value: id
│  └─ rightOperand
│     └─ value: 1000
└─ rightOperand
   └─ value: true
```

Would it be possible to add an option to display the class names like in the first example, so the nodes type are visible?

Maybe like this:

```
[AndOperator]
├─ leftOperand [EqualsOperator]
│  ├─ leftOperand [DotOperator]
│  │  ├─ leftOperand [RefLiteral]
│  │  │  └─ value: message
│  │  └─ rightOperand [RefLiteral]
│  │     └─ value: id
│  └─ rightOperand [NumberLiteral]
│     └─ value: 1000
└─ rightOperand [BooleanLiteral]
   └─ value: true
```

Thanks a lot for your feedback!

Kind regards,
Timo

**Comment by simlu** [comment]
I think this is a valid feature request. Let me think about how this would be best implemented!

**Comment by simlu** [comment]
Here is a PR that should address your situation: https://github.com/blackflux/object-treeify/pull/1064

**Comment by simlu** [comment]
Kk, released. You should be able to handle your case by provding e.g. ``renderFn: (node) => `: ${node}` ``

I'm closing this ticket, but please don't hesitate to ask if you have any questions!

**Comment by skjardenCode** [comment]
Hey @simlu,

oh wow - I hadn't had the chance to come back to this thread since I opened the issue until now... and you already implemented that feature! 😮

That's awesome! I tried it right away:

```
console.log( `[${expression.constructor.name}]` );
console.log( treeify( expression, {
  renderFn: ( node ) => {
    if ( [ 'boolean', 'string', 'number' ].includes( typeof node ) ) {
      return `: ${node}`;
    }

    if ( node instanceof Expression ) {
      return `: [${node.constructor.name}]`;
    } else {
      return '';
    }
  }
} ) );
```

Which gives me:

```
[AndOperator]
├─ leftOperand: [EqualsOperator]
│  ├─ leftOperand: [DotOperator]
│  │  ├─ leftOperand: [RefLiteral]
│  │  │  └─ value: message
│  │  └─ rightOperand: [RefLiteral]
│  │     └─ value: id
│  └─ rightOperand: [NumberLiteral]
│     └─ value: 1000
└─ rightOperand: [EqualsOperator]
   ├─ leftOperand: [DotOperator]
   │  ├─ leftOperand: [RefLiteral]
   │  │  └─ value: field
   │  └─ rightOperand: [RefLiteral]
   │     └─ value: id
   └─ rightOperand: [NumberLiteral]
      └─ value: 2000
```

This is really helpful, thanks a lot !

One minor thing: When I use the classic `console.log`, the actual root object is printed. Do get the root node displayed with `object-treeify`, I have to log it separately right before calling treeify.

It would be nice to have an option to let treeify also render the root node like in my example.

Then again, I'm not sure if that is a valid feature request.

**Comment by simlu** [comment]
We're getting into edge case territory for sure. How about calling `{ expression }` instead of `expression`?

This library would be easily implemented using [object-scan](https://github.com/blackflux/object-scan) and then you really have full flexibility. I'm a bit hesitant to add more features to this. It's meant to be a quick and easy way to visualize a hierarchy and "just work". Not something where you expect a ton of different settings. 

Let me see what an object-scan implementation would look like and then that could be used for all the edge cases like this.

**Comment by simlu** [comment]
I also think that logging it as a separate line as you're doing is acceptable.

**Comment by simlu** [comment]
Re-opened this for now with a wip pr here: https://github.com/blackflux/object-treeify/pull/1068/files

**Comment by simlu** [comment]
@skjardenCode I've released that PR above. It is technically a breaking change, but since you are most likely the only person using it, this should be fine to do as a minor release. Let me know if that fully solves your use case.

Closing this again =)

**Comment by skjardenCode** [comment]
@simlu 
I'm sorry for the late answer - thanks a lot for that wip PR, but I think you are totally right in saying, that adding the root node is an edge case and should not be part of this util.

So I agree, not adding rendering of the root node.

**Comment by simlu** [comment]
@skjardenCode No worries. This is released however and should work as expected with the root node now!
