### ISSUE TITLE
make this compatible with the browser

### ISSUE THREAD

**Issue by bboydflo** [blackflux/object-treeify#873]
instead of using assert from nodejs you can use this package https://www.npmjs.com/package/assert thus making this package work both in nodejs as well as in the browser.

**Comment by simlu** [comment]
I'm not sure I want to add a dependency to this package... Are there alternatives? Would `console.assert` work?

**Comment by simlu** [comment]
Would this work?
https://github.com/blackflux/object-treeify/pull/874/files

**Comment by bboydflo** [comment]
I think it would, and it's an elegant solution :)

**Comment by simlu** [comment]
Released in https://github.com/blackflux/object-treeify/releases/tag/v1.1.30

Feel free to reopen this ticket if that doesn't solve it for you!

**Comment by bboydflo** [comment]
thanks a lot!
